model = "gpt-6-astra"
model_reasoning_effort = "max"

[projects."/Users/ddd/dev/dddenis/astrolabe"]
trust_level = "trusted"

[projects."/Users/ddd/.nix"]
trust_level = "trusted"

[projects."/Users/ddd/dev/complyance/main/main-2"]
trust_level = "trusted"

[projects."/Users/ddd/dev/dddenis/tradingview"]
trust_level = "trusted"

[projects."/Users/ddd/dev/complyance/main/main-1"]
trust_level = "trusted"

[projects."/Users/ddd/dev/dddenis/pi-extensions"]
trust_level = "trusted"

[projects."/Users/ddd/dev/dddenis/complyance-kit"]
trust_level = "trusted"

[tui]
status_line = ["model-with-reasoning", "current-dir", "context-remaining", "five-hour-limit", "weekly-limit", "task-progress"]
status_line_use_colors = true
theme = "gruvbox-dark"

[tui.model_availability_nux]
"gpt-5.5" = 4
"gpt-5.6-sol" = 4
gpt-6-astra = 4

[hooks.state]

[hooks.state."/Users/ddd/dev/dddenis/astrolabe/.codex/hooks.json:post_tool_use:0:0"]
trusted_hash = "sha256:ac0f9d26f9f7a2a2fd62ea5b54d85752f6ab88589da153c3949e109305a31e21"

[hooks.state."superpowers@personal:hooks/hooks-codex.json:session_start:0:0"]
trusted_hash = "sha256:687e7af87f0cb59b1bcc71d368e097304b45d84999c90dc97358a22811691a3f"

[hooks.state."/Users/ddd/.codex/hooks.json:session_start:0:0"]
trusted_hash = "sha256:44a5a5d825f21548320c61409c1022948a795f913d438b25ab99e53e3516ec6c"
enabled = true

[[skills.config]]
path = "/Users/ddd/.codex/plugins/cache/openai-curated/superpowers/63976030/skills/finishing-a-development-branch/SKILL.md"
enabled = false

[notice]
hide_rate_limit_model_nudge = true

[plugins."superpowers@personal"]
enabled = true
