keys:
  - &ddd-pc age14f0us3adgmddwjdlldynce969n9p89tsze6v7ajlt8z44k89psgsue9v4r
  - &ddd-complyance age1yslk8xkm4f259meg0qdv4z6qudzuhjfvd7hpkc4pc9ny9nkzeyrq8ec2x2
creation_rules:
  - path_regex: ^(home|hosts)/ddd-pc/secrets.yaml$
    key_groups:
      - age:
          - *ddd-pc
  - path_regex: ^(home|hosts)/ddd-complyance/secrets.yaml$
    key_groups:
      - age:
          - *ddd-complyance
