{
  imports = [
    ./astro.nix
    ./completion.nix
    ./git.nix
    ./go.nix
    ./haskell.nix
    ./json.nix
    ./lsp.nix
    ./neovim.nix
    ./nix.nix
    ./python.nix
    ./rust.nix
    ./shell.nix
    ./sql.nix
    ./status-line.nix
    ./telescope.nix
    ./terraform.nix
    ./theme.nix
    ./treesitter.nix
    ./typescript.nix
  ];
}
